### ISSUE TITLE
Unexpected character '�' after upgrade

### ISSUE THREAD

**Issue by blumgart** [sidebase/nuxt-session#34]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `app`, `build`, `googleFonts`, `modules`, `session`, `image`, `routeRules`, `runtimeConfig`, `strapi`
- Runtime Modules:  `@sidebase/nuxt-session@0.2.5`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/strapi@1.6.3`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`, `@vueuse/nuxt@9.6.0`, `nuxt-icon@0.1.7`, `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.5`
- Build Modules:    `-`
------------------------------

### Describe the bug

After upgrade from 0.2.3 to 0.2.5 and trying `yarn build` i get this error:

```
MZ�♥♦���☺▼�� �!�☺L�!This program cannot be run in DOS mode.
     ^
�n'�R�n'�Richo'�PEd��sjc�" �U��e'�=R��a'�=R�f'�=R��F'�U�l'�o'��'�R��g'�R�n'�R
☻↔�☺↑☺↑�►�☺►☻♠♠@♥♦☻`☺►►►►►p�☻�☻¶�☻( ♥�☺�☻$♥0�☻pЅ☻8☺☻�☻\�☻@.text0�☺►�☺♦ `.rdata��☻��☺@@.datap▼�☻�☻@�.pdata$☻∟�☻@@_RDATA�►♥☻�☻@@.rsrc�☺ ♥☻�☻@@.reloc00�☻3�H��(H�%��☺3�H��(�������������H�♣�}☻H�☺H�H�H�������������H�H�♣♣z☻H��HE���������������@SH��0H�♣��☻H��H��t☻��H�♥H���P►E3�H�D$ E3�3�3��������������������������@SH�� H�♣+}☻H��H�☺��☺t
-y☻耙����������������H�☺�������������@SH�� H�Q@H��H��►r-H�I(H��H��►r↑L�A�H��'I+�H�A�H��▼wMI��蠈H�C8H�♣↓|☻H�C@�C(H�♥H�S↑H��t↑�{ u


 ERROR  Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

  at error (/E:/Projects/ns-project/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (/E:/Projects/ns-project/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.tryParse (/E:/Projects/ns-project/node_modules/rollup/dist/es/shared/rollup.js:12806:25)
  at Module.setSource (/E:/Projects/ns-project/node_modules/rollup/dist/es/shared/rollup.js:12711:24)
  at ModuleLoader.addModuleSource (/E:/Projects/ns-project/node_modules/rollup/dist/es/shared/rollup.js:21959:20)
```

Similar problem - nuxt/framework#7923

`npm ls argon2`

```
PS E:\Projects\ns-project> npm ls argon2
ns-project@ E:\Projects\ns-project
└─┬ @sidebase/nuxt-session@0.2.5
  └── argon2@0.30.2
```

**Comment by BracketJohn** [comment]
Hey @blumgart, thanks for the issue!

pinging @Voltra -> interesting that somebody switched to bcrypt because of it here: https://github.com/nuxt/framework/issues/7923 (very good  link, thanks @blumgart)

**Comment by chexburger** [comment]
Encountering the same issue. Resolved once the package was removed.

**Comment by chexburger** [comment]
@BracketJohn Just confirmed Argon2 to be the issue preventing building.

```js
import * as bcrypt from 'bcrypt';
. . .
export const hashIpAddress = (ip) => !ip ? Promise.resolve(void 0) : bcrypt.hashSync(ip);
export const ipAddressesMatch = (ip, ipHash) => !ip && !ipHash ? Promise.resolve(false) : bcrypt.compareSync(ip, ipHash);
```
That snippet does not use any salt rounds and defaults to 10. Replacing those respective lines from Argon2 to bcrypt fixes the problem with no build issues.
https://github.com/sidebase/nuxt-session/blob/main/src/runtime/server/middleware/session/ipPinning.ts
