### ISSUE TITLE
Nuxt Fatal Error

### ISSUE THREAD

**Issue by Noflare** [sidebase/nuxt-session#56]
### Describe the bug

When i install Nuxt-Session i have an error

### Logs

```shell
FATAL  Cannot read properties of undefined (reading 'session')                                                                                                                                                           13:41:52  

  at setup (/C:/Users/Noflare/Desktop/EconomYx/app.economyx.fr/economyxdashboard/node_modules/@sidebase/nuxt-session/dist/module.mjs:51:74)
  at ModuleContainer.normalizedModule (/C:/Users/Noflare/Desktop/EconomYx/app.economyx.fr/economyxdashboard/node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:55:5)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)


   ╭────────────────────────────────────────────────────────────────────────╮
   │                                                                        │
   │   ✖ Nuxt Fatal Error                                                   │
   │                                                                        │
   │   TypeError: Cannot read properties of undefined (reading 'session')   │
   │                                                                        │
   ╰────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by BracketJohn** [comment]
Hey @Noflare 👋 

Thanks for the issue.

Right now this looks like a different problem to me: Your error message says "trying to access property session of undefined@ -> this means that "event.context" is undefined and not (necessarily) "event.context.session".

So it rather seems to be a setup problem with your Nuxt 3 setup OR a problem with where you're accessing the "event.context".

Please look into this, and if you fix that and then "session" itself is undefined we can look into the problem here.
